apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: coderag-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: coderag-app-config
    patch: |-
      - op: replace
        path: /data/NEO4J_URI
        value: bolt://neo4j.prod.svc.cluster.local:7687
      - op: replace
        path: /data/REDIS_URL
        value: redis://redis.prod.svc.cluster.local:6379/0
images:
  - name: kdb-rag-docs
    newName: ghcr.io/gherrerz/kdb-rag-docs
    newTag: stable
