apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coderag
resources:
  - namespace.yaml
  - configmap-app.yaml
  - pvc-data.yaml
  - deployment-api.yaml
  - service-api.yaml
  - deployment-worker.yaml
# Optional in production ingress controllers.
# - ingress-api.yaml
