apiVersion: v1
kind: Secret
metadata:
  name: coderag-app-secrets
  namespace: coderag
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  VERTEX_AI_API_KEY: ""
  VERTEX_PROJECT_ID: ""
  NEO4J_PASSWORD: "password"
